name: cs442_mp3
description: "Yahtzee!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_animation_progress_bar: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


